name: weather_app
description: "Weather application for Android devices."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:

  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
